baseurl = "http://refreshannapolisvalley.com/"
languageCode = "en-ca"
title = "Refresh Annapolis Valley"
theme = "f5"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "G-KE00Q8J5Y2"

enableRobotsTXT = true

[taxonomies]
subject = "subjects"
person = "people"
organization = "organizations"
topic = "topics"
project = "projects"

[params]
  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  description = "Refresh is a community of designers and developers working to refresh the creative, technical, and professional culture of New Media endeavors in the Annapolis Valley while promoting design, technology, usability, and standards."

  # Google API key for Google Maps
  googleAPIKey = "AIzaSyCvEYk4fnzW_QfClB_mWEZPItiuHzYdw3A"

  facebookAppId = "641839162645576"

  facebookPixelId = "1716195941798152"

  facebookPage = "RefreshAnnapolisValley"

  googleSiteVerification = "mP_EL_wJIw8NvUckIyH7Pvr2u4tXhqnWwj81zdn3i3Q"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Events"
  url = "event"
  weight = 1

[[menu.main]]
  name = "Topics"
  url = "topics"
  weight = 2

[[menu.main]]
  name = "People"
  url = "person"
  weight = 3

[[menu.main]]
  name = "Orgs"
  url = "organization"
  weight = 4

[[menu.main]]
  name = "Projects"
  url = "project"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "post"
  weight = 6

[[menu.main]]
  name = "Support"
  url = "support"
  weight = 7
